### ISSUE TITLE
errors on response headers

### ISSUE THREAD

**Issue by didotb** [riramar/hsecscan#4]
`>> RESPONSE HEADERS DETAILS <<
Traceback (most recent call last):
  File "/usr/bin/hsecscan.py", line 137, in <module>
    main()
  File "/usr/bin/hsecscan.py", line 132, in main
    scan(args.URL, args.redirect, args.useragent, args.postdata, args.proxy)
  File "/usr/bin/hsecscan.py", line 104, in scan
    check_header(header)
  File "/usr/bin/hsecscan.py", line 52, in check_header
    cur.execute('SELECT "Header Field Name", "Reference", "Security Description", "Security Reference", "Recommendations", "CWE", "CWE URL" FROM headers WHERE "Enable" = "Y" AND "Header Field Name" = ? COLLATE NOCASE', t)
sqlite3.OperationalError: no such table: headers`

hmm... I think I'm doing something wrong here...

**Comment by riramar** [comment]
Do you have the file hsecscan.db under the same directory as hsecscan.py?
Without the database hsecscan.py won't work.

**Comment by didotb** [comment]
yes I do, both .db and .tsv just to make sure

**Comment by riramar** [comment]
The requirement is only hsecscan.db file. The .tsv file is just a text file with the same content for easy check.
The error log from your post is saying "no such table: headers" which means that sqlite3 was unable to find the table "headers".
Try this command below in order to list the tables from your hsecscan.db:

`$ sqlite3 hsecscan.db '.tables'`
`headers`

If the command above doesn't return the "headers" table there is something wrong with your hsecscan.db.
In this case you can download it again from here https://raw.githubusercontent.com/riramar/hsecscan/master/hsecscan.db.

**Comment by riramar** [comment]
Just include a db file checking so you can update and use.
Thanks!
